import type {
  Category,
  Collection,
  Customer,
  Order,
  Product,
  Review,
  Vendor,
} from "./types";

import imgTea from "@/assets/p-tea.jpg";
import imgCoffee from "@/assets/p-coffee.jpg";
import imgHoney from "@/assets/p-honey.jpg";
import imgSpice from "@/assets/p-spice.jpg";
import imgPashmina from "@/assets/p-pashmina.jpg";
import imgCeramic from "@/assets/p-ceramic.jpg";
import imgIncense from "@/assets/p-incense.jpg";
import imgSkincare from "@/assets/p-skincare.jpg";
import imgFelt from "@/assets/p-felt.jpg";
import imgEditorialHome from "@/assets/editorial-home.jpg";
import imgEditorialCraft from "@/assets/editorial-craft.jpg";
import imgEditorialWellness from "@/assets/editorial-wellness.jpg";
import imgNepal from "@/assets/nepal-origin.jpg";

export const images = {
  tea: imgTea,
  coffee: imgCoffee,
  honey: imgHoney,
  spice: imgSpice,
  pashmina: imgPashmina,
  ceramic: imgCeramic,
  incense: imgIncense,
  skincare: imgSkincare,
  felt: imgFelt,
  editorialHome: imgEditorialHome,
  editorialCraft: imgEditorialCraft,
  editorialWellness: imgEditorialWellness,
  nepal: imgNepal,
};

export const categories: Category[] = [
  {
    id: "cat_tea",
    handle: "tea-coffee",
    name: "Tea & Coffee",
    description:
      "Single-estate leaves and high-altitude beans, sourced from growers we know by name.",
    featured: true,
    children: [
      { handle: "tea-coffee", name: "Loose Leaf Tea" },
      { handle: "tea-coffee", name: "Specialty Coffee" },
      { handle: "tea-coffee", name: "Brewing Tools" },
    ],
  },
  {
    id: "cat_pantry",
    handle: "pantry",
    name: "Pantry & Provisions",
    description: "Honey, spices, grains and preserves from small-batch producers.",
    featured: true,
    children: [
      { handle: "pantry", name: "Honey" },
      { handle: "pantry", name: "Spices" },
      { handle: "pantry", name: "Grains & Oils" },
    ],
  },
  {
    id: "cat_wellness",
    handle: "wellness",
    name: "Wellness & Herbs",
    description: "Botanical remedies, adaptogens and rituals rooted in Himalayan practice.",
    featured: true,
    children: [
      { handle: "wellness", name: "Herbal Remedies" },
      { handle: "wellness", name: "Incense & Ritual" },
      { handle: "wellness", name: "Supplements" },
    ],
  },
  {
    id: "cat_beauty",
    handle: "beauty",
    name: "Beauty & Skincare",
    description: "Clean formulations built on cold-pressed oils and mountain botanicals.",
    children: [
      { handle: "beauty", name: "Face" },
      { handle: "beauty", name: "Body" },
      { handle: "beauty", name: "Hair" },
    ],
  },
  {
    id: "cat_textiles",
    handle: "textiles",
    name: "Textiles & Apparel",
    description: "Cashmere, hemp and hand-loomed cloth made by weaving cooperatives.",
    featured: true,
    children: [
      { handle: "textiles", name: "Scarves & Shawls" },
      { handle: "textiles", name: "Knitwear" },
      { handle: "textiles", name: "Blankets" },
    ],
  },
  {
    id: "cat_home",
    handle: "home-craft",
    name: "Home & Craft",
    description: "Ceramics, felt, brass and woven objects for a considered home.",
    featured: true,
    children: [
      { handle: "home-craft", name: "Ceramics" },
      { handle: "home-craft", name: "Storage" },
      { handle: "home-craft", name: "Lighting" },
    ],
  },
];

export const vendors: Vendor[] = [
  {
    id: "ven_kanchan",
    handle: "kanchan-tea-estate",
    name: "Kanchan Tea Estate",
    tagline: "Single-estate orthodox tea from Ilam",
    description:
      "Founded on a terraced ridge at 1,900m, Kanchan has been hand-plucking orthodox tea for three generations. Every lot is withered, rolled and dried within eight hours of harvest.",
    location: "Ilam, Nepal",
    since: 1978,
    rating: 4.9,
    productCount: 18,
    heroImage: imgNepal,
  },
  {
    id: "ven_himal",
    handle: "himal-roasters",
    name: "Himal Roasters",
    tagline: "High-altitude arabica, roasted in Kathmandu",
    description:
      "A micro-roastery working directly with 240 smallholder farms across Gulmi and Lalitpur, paying above market for cherry picked at peak ripeness.",
    location: "Kathmandu, Nepal",
    since: 2014,
    rating: 4.8,
    productCount: 12,
    heroImage: imgEditorialCraft,
  },
  {
    id: "ven_madhu",
    handle: "madhu-apiaries",
    name: "Madhu Apiaries",
    tagline: "Wild cliff honey and single-flora jars",
    description:
      "Working with traditional honey hunters in Lamjung, Madhu bottles raw, unpasteurised honey traceable to a single cliff or forest.",
    location: "Lamjung, Nepal",
    since: 2009,
    rating: 4.7,
    productCount: 9,
    heroImage: imgEditorialWellness,
  },
  {
    id: "ven_sherpa",
    handle: "sherpa-weaves",
    name: "Sherpa Weaves",
    tagline: "Hand-loomed cashmere and hemp",
    description:
      "A women-led weaving cooperative of 60 artisans producing pashmina, hemp and allo textiles on traditional pit looms.",
    location: "Bhaktapur, Nepal",
    since: 1996,
    rating: 4.9,
    productCount: 24,
    heroImage: imgEditorialCraft,
  },
  {
    id: "ven_terra",
    handle: "terra-studio",
    name: "Terra Studio",
    tagline: "Stoneware for everyday ritual",
    description:
      "A small ceramics studio throwing unglazed and matte-glazed stoneware from local Kathmandu valley clay.",
    location: "Patan, Nepal",
    since: 2018,
    rating: 4.8,
    productCount: 15,
    heroImage: imgEditorialHome,
  },
  {
    id: "ven_aroma",
    handle: "aranya-botanicals",
    name: "Aranya Botanicals",
    tagline: "Wild-harvested herbal skincare",
    description:
      "Cold-pressed oils, seabuckthorn and Himalayan botanicals formulated in small batches with no synthetic fragrance.",
    location: "Pokhara, Nepal",
    since: 2016,
    rating: 4.7,
    productCount: 21,
    heroImage: imgEditorialWellness,
  },
];

export const collections: Collection[] = [
  {
    id: "col_nepal",
    handle: "nepal-origin",
    title: "Nepal Origin",
    subtitle: "Made in Nepal. Ready for the world.",
    description:
      "Producers, cooperatives and studios working at altitude — tea, coffee, honey, herbs, spices, textiles and craft, shipped direct.",
    image: imgNepal,
    editorial: true,
  },
  {
    id: "col_morning",
    handle: "the-morning-ritual",
    title: "The Morning Ritual",
    subtitle: "Brew, pour, begin",
    description:
      "A tightly edited set of leaves, beans and stoneware for the first hour of the day.",
    image: imgEditorialHome,
    editorial: true,
  },
  {
    id: "col_quiet",
    handle: "quiet-materials",
    title: "Quiet Materials",
    subtitle: "Hemp, allo, clay, brass",
    description:
      "Objects made from four honest materials, finished by hand and built to age well.",
    image: imgEditorialCraft,
    editorial: true,
  },
  {
    id: "col_wellness",
    handle: "altitude-wellness",
    title: "Altitude Wellness",
    subtitle: "Botanicals from 3,000m",
    description:
      "Adaptogens, tonics and ritual objects drawn from Himalayan herbal practice.",
    image: imgEditorialWellness,
    editorial: true,
  },
];

interface Seed {
  handle: string;
  title: string;
  subtitle: string;
  price: number;
  compareAt?: number;
  image: string;
  categoryId: string;
  vendorId: string;
  collections: string[];
  tags: string[];
  material: string;
  rating: number;
  reviewCount: number;
  popularity: number;
  daysOld: number;
  stock: number;
  description: string;
  story?: string;
  variantLabel: string;
  variants: { title: string; delta: number }[];
  specs: { label: string; value: string }[];
}

const seeds: Seed[] = [
  {
    handle: "ilam-first-flush-black-tea",
    title: "Ilam First Flush Black Tea",
    subtitle: "Orthodox, hand-plucked, spring 2026 lot",
    price: 2400,
    image: images.tea,
    categoryId: "cat_tea",
    vendorId: "ven_kanchan",
    collections: ["col_nepal", "col_morning"],
    tags: ["tea", "single-estate", "spring-harvest"],
    material: "Camellia sinensis",
    rating: 4.9,
    reviewCount: 212,
    popularity: 98,
    daysOld: 6,
    stock: 42,
    description:
      "A bright, muscatel first flush picked in the second week of spring. Two leaves and a bud, withered overnight and rolled the same morning.",
    story:
      "Kanchan's pluckers work the eastern ridge before the mist lifts, when the leaf is still cool. The lot is small — 340kg across the whole season.",
    variantLabel: "Size",
    variants: [
      { title: "50g tin", delta: 0 },
      { title: "100g pouch", delta: 1600 },
      { title: "250g pouch", delta: 4200 },
    ],
    specs: [
      { label: "Altitude", value: "1,900m" },
      { label: "Harvest", value: "First flush, spring" },
      { label: "Steep", value: "3 min at 90°C" },
    ],
  },
  {
    handle: "himalayan-green-tea",
    title: "High Ridge Green Tea",
    subtitle: "Pan-fired, vegetal and clean",
    price: 1900,
    image: images.tea,
    categoryId: "cat_tea",
    vendorId: "ven_kanchan",
    collections: ["col_nepal", "col_morning"],
    tags: ["tea", "green", "daily"],
    material: "Camellia sinensis",
    rating: 4.6,
    reviewCount: 96,
    popularity: 74,
    daysOld: 40,
    stock: 60,
    description:
      "Pan-fired within hours of plucking to lock in a fresh, grassy character with a soft chestnut finish.",
    variantLabel: "Size",
    variants: [
      { title: "50g tin", delta: 0 },
      { title: "100g pouch", delta: 1200 },
    ],
    specs: [
      { label: "Altitude", value: "1,750m" },
      { label: "Steep", value: "2 min at 80°C" },
    ],
  },
  {
    handle: "gulmi-washed-arabica",
    title: "Gulmi Washed Arabica",
    subtitle: "Stone fruit, cocoa, long finish",
    price: 2200,
    compareAt: 2600,
    image: images.coffee,
    categoryId: "cat_tea",
    vendorId: "ven_himal",
    collections: ["col_nepal", "col_morning"],
    tags: ["coffee", "washed", "single-origin"],
    material: "Arabica",
    rating: 4.8,
    reviewCount: 341,
    popularity: 96,
    daysOld: 12,
    stock: 88,
    description:
      "Cherry picked at 1,600m, fermented 18 hours and dried on raised beds. Roasted medium for filter.",
    story:
      "Himal pays a premium per kilo directly to 240 smallholder farms, with harvest data recorded per lot.",
    variantLabel: "Grind",
    variants: [
      { title: "Whole bean 250g", delta: 0 },
      { title: "Filter grind 250g", delta: 0 },
      { title: "Whole bean 1kg", delta: 5400 },
    ],
    specs: [
      { label: "Process", value: "Fully washed" },
      { label: "Roast", value: "Medium / filter" },
      { label: "Altitude", value: "1,600m" },
    ],
  },
  {
    handle: "dark-roast-espresso",
    title: "Kathmandu Espresso Roast",
    subtitle: "Dense, chocolate-forward, for milk",
    price: 2100,
    image: images.coffee,
    categoryId: "cat_tea",
    vendorId: "ven_himal",
    collections: ["col_morning"],
    tags: ["coffee", "espresso", "blend"],
    material: "Arabica",
    rating: 4.5,
    reviewCount: 128,
    popularity: 81,
    daysOld: 70,
    stock: 51,
    description: "A two-farm blend roasted long for body, built to hold up under milk.",
    variantLabel: "Grind",
    variants: [
      { title: "Whole bean 250g", delta: 0 },
      { title: "Espresso grind 250g", delta: 0 },
    ],
    specs: [
      { label: "Roast", value: "Dark / espresso" },
      { label: "Blend", value: "Gulmi + Lalitpur" },
    ],
  },
  {
    handle: "wild-cliff-honey",
    title: "Wild Cliff Honey",
    subtitle: "Raw, unpasteurised, single harvest",
    price: 3400,
    image: images.honey,
    categoryId: "cat_pantry",
    vendorId: "ven_madhu",
    collections: ["col_nepal", "col_wellness"],
    tags: ["honey", "raw", "wild-harvest"],
    material: "Raw honey",
    rating: 4.9,
    reviewCount: 187,
    popularity: 94,
    daysOld: 18,
    stock: 24,
    description:
      "Harvested from cliff colonies of Apis laboriosa by traditional honey hunters. Deep amber, resinous, faintly bitter.",
    story:
      "Two harvests a year, roped descents, no smoke beyond what the hunters have always used. Each jar is traceable to a single cliff face.",
    variantLabel: "Size",
    variants: [
      { title: "250g jar", delta: 0 },
      { title: "500g jar", delta: 2600 },
    ],
    specs: [
      { label: "Origin", value: "Lamjung cliffs" },
      { label: "Processing", value: "Raw, unfiltered" },
    ],
  },
  {
    handle: "chiuri-forest-honey",
    title: "Chiuri Forest Honey",
    subtitle: "Butter-soft, floral, creamed",
    price: 2200,
    image: images.honey,
    categoryId: "cat_pantry",
    vendorId: "ven_madhu",
    collections: ["col_nepal"],
    tags: ["honey", "single-flora"],
    material: "Raw honey",
    rating: 4.6,
    reviewCount: 74,
    popularity: 66,
    daysOld: 95,
    stock: 39,
    description: "A single-flora honey from chiuri blossom, naturally creamed to a soft set.",
    variantLabel: "Size",
    variants: [{ title: "300g jar", delta: 0 }],
    specs: [{ label: "Flora", value: "Chiuri blossom" }],
  },
  {
    handle: "timur-pepper",
    title: "Timur Mountain Pepper",
    subtitle: "Citrus, tingling, wild-gathered",
    price: 1400,
    image: images.spice,
    categoryId: "cat_pantry",
    vendorId: "ven_madhu",
    collections: ["col_nepal"],
    tags: ["spice", "wild-harvest", "pantry"],
    material: "Zanthoxylum",
    rating: 4.8,
    reviewCount: 156,
    popularity: 88,
    daysOld: 30,
    stock: 120,
    description:
      "Wild timur berries with a grapefruit-like lift and a slow, numbing warmth. Grind fresh over anything fatty.",
    variantLabel: "Size",
    variants: [
      { title: "40g", delta: 0 },
      { title: "100g", delta: 1500 },
    ],
    specs: [{ label: "Harvest", value: "Wild-gathered, autumn" }],
  },
  {
    handle: "himalayan-spice-blend",
    title: "Everyday Masala Blend",
    subtitle: "Stone-ground in small batches",
    price: 1200,
    image: images.spice,
    categoryId: "cat_pantry",
    vendorId: "ven_madhu",
    collections: [],
    tags: ["spice", "pantry", "blend"],
    material: "Spice blend",
    rating: 4.4,
    reviewCount: 61,
    popularity: 58,
    daysOld: 140,
    stock: 0,
    description: "Nine spices toasted and stone-ground weekly, balanced for daily cooking.",
    variantLabel: "Size",
    variants: [{ title: "80g", delta: 0 }],
    specs: [{ label: "Grind", value: "Stone-ground" }],
  },
  {
    handle: "cashmere-ridge-shawl",
    title: "Ridge Cashmere Shawl",
    subtitle: "Hand-loomed, 100% pashmina",
    price: 18500,
    compareAt: 21000,
    image: images.pashmina,
    categoryId: "cat_textiles",
    vendorId: "ven_sherpa",
    collections: ["col_nepal", "col_quiet"],
    tags: ["cashmere", "handwoven", "accessory"],
    material: "Cashmere",
    rating: 4.9,
    reviewCount: 268,
    popularity: 99,
    daysOld: 9,
    stock: 17,
    description:
      "Woven on a pit loom over four days from combed Chyangra cashmere, with a hand-twisted fringe.",
    story:
      "Sixty women weave for Sherpa Weaves across Bhaktapur, each piece signed with the weaver's initials on the label.",
    variantLabel: "Colour",
    variants: [
      { title: "Oat", delta: 0 },
      { title: "Clay", delta: 0 },
      { title: "Charcoal", delta: 800 },
    ],
    specs: [
      { label: "Material", value: "100% Chyangra cashmere" },
      { label: "Size", value: "200 × 70 cm" },
      { label: "Weight", value: "240g" },
    ],
  },
  {
    handle: "hemp-throw-blanket",
    title: "Allo Hemp Throw",
    subtitle: "Naturally dyed, pit-loom woven",
    price: 9800,
    image: images.pashmina,
    categoryId: "cat_textiles",
    vendorId: "ven_sherpa",
    collections: ["col_quiet"],
    tags: ["hemp", "handwoven", "home"],
    material: "Hemp",
    rating: 4.7,
    reviewCount: 82,
    popularity: 72,
    daysOld: 55,
    stock: 22,
    description:
      "Wild nettle fibre spun by hand in Sankhuwasabha, woven into a heavyweight throw that softens with use.",
    variantLabel: "Colour",
    variants: [
      { title: "Undyed", delta: 0 },
      { title: "Madder", delta: 600 },
    ],
    specs: [
      { label: "Material", value: "Allo (Himalayan nettle)" },
      { label: "Size", value: "150 × 200 cm" },
    ],
  },
  {
    handle: "stoneware-cup-set",
    title: "Terra Stoneware Cup & Saucer",
    subtitle: "Wheel-thrown, matte clay glaze",
    price: 4200,
    image: images.ceramic,
    categoryId: "cat_home",
    vendorId: "ven_terra",
    collections: ["col_morning", "col_quiet"],
    tags: ["ceramic", "handmade", "tableware"],
    material: "Stoneware",
    rating: 4.8,
    reviewCount: 143,
    popularity: 90,
    daysOld: 21,
    stock: 34,
    description:
      "Thrown from Kathmandu valley clay and fired to 1,240°C. Each cup varies slightly in tone and weight.",
    variantLabel: "Set",
    variants: [
      { title: "Single", delta: 0 },
      { title: "Set of two", delta: 3600 },
      { title: "Set of four", delta: 7900 },
    ],
    specs: [
      { label: "Capacity", value: "180ml" },
      { label: "Care", value: "Dishwasher safe" },
    ],
  },
  {
    handle: "felt-storage-baskets",
    title: "Wool Felt Basket Pair",
    subtitle: "Hand-felted, undyed and charcoal",
    price: 5600,
    image: images.felt,
    categoryId: "cat_home",
    vendorId: "ven_terra",
    collections: ["col_quiet"],
    tags: ["felt", "storage", "handmade"],
    material: "Wool",
    rating: 4.5,
    reviewCount: 58,
    popularity: 63,
    daysOld: 66,
    stock: 29,
    description: "Wet-felted from New Zealand wool by hand, holding shape without stiffeners.",
    variantLabel: "Size",
    variants: [
      { title: "Small pair", delta: 0 },
      { title: "Large pair", delta: 2400 },
    ],
    specs: [{ label: "Material", value: "100% wool felt" }],
  },
  {
    handle: "juniper-incense",
    title: "Juniper & Sal Incense",
    subtitle: "Rolled by hand, no bamboo core",
    price: 1600,
    image: images.incense,
    categoryId: "cat_wellness",
    vendorId: "ven_aroma",
    collections: ["col_wellness", "col_nepal"],
    tags: ["incense", "ritual", "wellness"],
    material: "Botanical",
    rating: 4.7,
    reviewCount: 204,
    popularity: 86,
    daysOld: 33,
    stock: 74,
    description:
      "High-altitude juniper and sal resin, hand-rolled without charcoal or synthetic binder.",
    variantLabel: "Pack",
    variants: [
      { title: "30 sticks", delta: 0 },
      { title: "30 sticks + brass holder", delta: 1900 },
    ],
    specs: [
      { label: "Burn time", value: "~35 min" },
      { label: "Ingredients", value: "Juniper, sal resin, herbs" },
    ],
  },
  {
    handle: "shilajit-resin",
    title: "Purified Shilajit Resin",
    subtitle: "Lab-tested, 30g jar",
    price: 4900,
    image: images.honey,
    categoryId: "cat_wellness",
    vendorId: "ven_aroma",
    collections: ["col_wellness"],
    tags: ["wellness", "supplement", "adaptogen"],
    material: "Mineral resin",
    rating: 4.6,
    reviewCount: 311,
    popularity: 92,
    daysOld: 48,
    stock: 45,
    description:
      "Collected above 4,000m, filtered through spring water and sun-dried. Each batch is heavy-metal tested.",
    variantLabel: "Size",
    variants: [
      { title: "20g", delta: 0 },
      { title: "30g", delta: 1800 },
    ],
    specs: [
      { label: "Testing", value: "Third-party, per batch" },
      { label: "Serving", value: "Pea-sized, daily" },
    ],
  },
  {
    handle: "seabuckthorn-face-oil",
    title: "Seabuckthorn Face Oil",
    subtitle: "Cold-pressed, 30ml",
    price: 3800,
    image: images.skincare,
    categoryId: "cat_beauty",
    vendorId: "ven_aroma",
    collections: ["col_wellness", "col_nepal"],
    tags: ["skincare", "oil", "clean-beauty"],
    material: "Botanical oil",
    rating: 4.8,
    reviewCount: 176,
    popularity: 89,
    daysOld: 15,
    stock: 63,
    description:
      "Mustang seabuckthorn pressed with jojoba and rosehip. Fast-absorbing, no synthetic fragrance.",
    story:
      "Seabuckthorn grows wild along the Kali Gandaki. Harvest is short and entirely manual.",
    variantLabel: "Size",
    variants: [
      { title: "15ml", delta: -1400 },
      { title: "30ml", delta: 0 },
    ],
    specs: [
      { label: "Skin type", value: "All, incl. sensitive" },
      { label: "Ingredients", value: "9 botanicals" },
    ],
  },
  {
    handle: "himalayan-clay-mask",
    title: "Mineral Clay Mask",
    subtitle: "Multani clay and neem",
    price: 2600,
    image: images.skincare,
    categoryId: "cat_beauty",
    vendorId: "ven_aroma",
    collections: [],
    tags: ["skincare", "mask", "clean-beauty"],
    material: "Clay",
    rating: 4.3,
    reviewCount: 47,
    popularity: 54,
    daysOld: 120,
    stock: 80,
    description: "A weekly clay mask with neem and turmeric, mixed fresh with water or honey.",
    variantLabel: "Size",
    variants: [{ title: "80g", delta: 0 }],
    specs: [{ label: "Use", value: "1–2× weekly" }],
  },
  {
    handle: "brass-pour-over-stand",
    title: "Brass Pour-Over Stand",
    subtitle: "Hand-spun, unlacquered",
    price: 7400,
    image: images.ceramic,
    categoryId: "cat_home",
    vendorId: "ven_terra",
    collections: ["col_morning", "col_quiet"],
    tags: ["brass", "brewing", "handmade"],
    material: "Brass",
    rating: 4.7,
    reviewCount: 39,
    popularity: 61,
    daysOld: 27,
    stock: 12,
    description: "Spun by Patan metalworkers and left unlacquered so it patinas with time.",
    variantLabel: "Finish",
    variants: [
      { title: "Raw brass", delta: 0 },
      { title: "Brushed", delta: 900 },
    ],
    specs: [{ label: "Fits", value: "Most 01/02 drippers" }],
  },
  {
    handle: "tulsi-tisane",
    title: "Tulsi & Lemongrass Tisane",
    subtitle: "Caffeine-free daily infusion",
    price: 1500,
    image: images.tea,
    categoryId: "cat_wellness",
    vendorId: "ven_kanchan",
    collections: ["col_wellness"],
    tags: ["tea", "herbal", "caffeine-free"],
    material: "Herbal",
    rating: 4.5,
    reviewCount: 91,
    popularity: 69,
    daysOld: 80,
    stock: 95,
    description: "Shade-dried tulsi with lemongrass and a little ginger — soft, clean, everyday.",
    variantLabel: "Size",
    variants: [
      { title: "60g", delta: 0 },
      { title: "150g", delta: 1300 },
    ],
    specs: [{ label: "Caffeine", value: "None" }],
  },
  {
    handle: "hand-knit-wool-scarf",
    title: "Hand-Knit Merino Scarf",
    subtitle: "Chunky rib, undyed merino",
    price: 6800,
    image: images.pashmina,
    categoryId: "cat_textiles",
    vendorId: "ven_sherpa",
    collections: [],
    tags: ["wool", "knitwear", "accessory"],
    material: "Merino wool",
    rating: 4.6,
    reviewCount: 66,
    popularity: 64,
    daysOld: 44,
    stock: 26,
    description: "Knit in a deep rib over two days, undyed and lightly milled.",
    variantLabel: "Colour",
    variants: [
      { title: "Natural", delta: 0 },
      { title: "Slate", delta: 0 },
    ],
    specs: [{ label: "Size", value: "180 × 26 cm" }],
  },
  {
    handle: "ceramic-serving-bowl",
    title: "Wide Serving Bowl",
    subtitle: "Speckled stoneware, 26cm",
    price: 5200,
    image: images.ceramic,
    categoryId: "cat_home",
    vendorId: "ven_terra",
    collections: ["col_quiet"],
    tags: ["ceramic", "tableware", "handmade"],
    material: "Stoneware",
    rating: 4.7,
    reviewCount: 52,
    popularity: 60,
    daysOld: 100,
    stock: 18,
    description: "A generous everyday bowl with a bare foot ring and a soft speckled glaze.",
    variantLabel: "Glaze",
    variants: [
      { title: "Oat", delta: 0 },
      { title: "Ash", delta: 0 },
    ],
    specs: [{ label: "Diameter", value: "26 cm" }],
  },
  {
    handle: "silver-tip-white-tea",
    title: "Silver Tip White Tea",
    subtitle: "Bud-only, sun-withered",
    price: 4600,
    image: images.tea,
    categoryId: "cat_tea",
    vendorId: "ven_kanchan",
    collections: ["col_nepal"],
    tags: ["tea", "white", "rare"],
    material: "Camellia sinensis",
    rating: 4.9,
    reviewCount: 88,
    popularity: 79,
    daysOld: 4,
    stock: 9,
    description:
      "Only unopened buds, sun-withered on bamboo trays. Honeyed, delicate, extremely limited.",
    variantLabel: "Size",
    variants: [{ title: "25g tin", delta: 0 }],
    specs: [
      { label: "Yield", value: "38kg per season" },
      { label: "Steep", value: "4 min at 80°C" },
    ],
  },
  {
    handle: "yak-wool-blanket",
    title: "Yak Wool Blanket",
    subtitle: "Handwoven, herringbone",
    price: 12400,
    image: images.pashmina,
    categoryId: "cat_textiles",
    vendorId: "ven_sherpa",
    collections: ["col_quiet", "col_nepal"],
    tags: ["wool", "handwoven", "home"],
    material: "Yak wool",
    rating: 4.8,
    reviewCount: 104,
    popularity: 84,
    daysOld: 62,
    stock: 14,
    description: "Warm without weight, woven in a fine herringbone from combed yak down.",
    variantLabel: "Colour",
    variants: [
      { title: "Ash", delta: 0 },
      { title: "Umber", delta: 0 },
    ],
    specs: [{ label: "Size", value: "130 × 200 cm" }],
  },
  {
    handle: "cold-pressed-mustard-oil",
    title: "Cold-Pressed Mustard Oil",
    subtitle: "Wood-pressed, unrefined",
    price: 1800,
    image: images.honey,
    categoryId: "cat_pantry",
    vendorId: "ven_madhu",
    collections: ["col_nepal"],
    tags: ["pantry", "oil", "cold-pressed"],
    material: "Mustard oil",
    rating: 4.4,
    reviewCount: 43,
    popularity: 52,
    daysOld: 150,
    stock: 55,
    description: "Pressed in a wooden ghani at low temperature, pungent and unfiltered.",
    variantLabel: "Size",
    variants: [
      { title: "500ml", delta: 0 },
      { title: "1L", delta: 1500 },
    ],
    specs: [{ label: "Process", value: "Wood-pressed" }],
  },
];

function buildProduct(seed: Seed, index: number): Product {
  const created = new Date(Date.now() - seed.daysOld * 86400000).toISOString();
  return {
    id: `prod_${index + 1}`,
    handle: seed.handle,
    title: seed.title,
    subtitle: seed.subtitle,
    description: seed.description,
    story: seed.story,
    images: [
      { url: seed.image, alt: `${seed.title} — product photograph` },
      { url: images.editorialCraft, alt: `${seed.title} — made by hand in Nepal` },
      { url: images.editorialHome, alt: `${seed.title} — styled in a home setting` },
    ],
    categoryId: seed.categoryId,
    collectionIds: seed.collections,
    vendorId: seed.vendorId,
    variants: seed.variants.map((v, i) => ({
      id: `var_${index + 1}_${i + 1}`,
      title: v.title,
      price: { amount: seed.price + v.delta, currency: "usd" },
      compareAtPrice: seed.compareAt
        ? { amount: seed.compareAt + v.delta, currency: "usd" }
        : undefined,
      inventoryQuantity: Math.max(0, seed.stock - i * 3),
      options: { [seed.variantLabel]: v.title },
    })),
    tags: seed.tags,
    material: seed.material,
    originCountry: "Nepal",
    nepalOrigin: true,
    rating: seed.rating,
    reviewCount: seed.reviewCount,
    createdAt: created,
    popularity: seed.popularity,
    specs: seed.specs,
  };
}

export const products: Product[] = seeds.map(buildProduct);

const reviewSeeds: Omit<Review, "id" | "productId">[] = [
  {
    author: "Marta L.",
    location: "Lisbon, PT",
    rating: 5,
    title: "Worth every cent",
    body: "Arrived in eight days, beautifully packed. The quality is well beyond what I expected at this price.",
    date: "2026-07-28",
    verified: true,
  },
  {
    author: "Devin R.",
    location: "Toronto, CA",
    rating: 5,
    title: "Repeat order",
    body: "Third time buying. Consistent from batch to batch, which is rare for small producers.",
    date: "2026-07-11",
    verified: true,
  },
  {
    author: "Aiko T.",
    location: "Osaka, JP",
    rating: 4,
    title: "Lovely, packaging could be sturdier",
    body: "The product itself is excellent. Outer box was a little dented but nothing inside was affected.",
    date: "2026-06-30",
    verified: true,
  },
  {
    author: "Sunita K.",
    location: "Kathmandu, NP",
    rating: 5,
    title: "Genuinely local",
    body: "Good to see producers I recognise getting a proper storefront and fair pricing.",
    date: "2026-06-04",
    verified: true,
  },
];

export const reviews: Review[] = products.flatMap((p, pi) =>
  reviewSeeds.map((r, ri) => ({
    ...r,
    id: `rev_${pi}_${ri}`,
    productId: p.id,
  })),
);

export const customer: Customer = {
  id: "cus_01",
  firstName: "Anya",
  lastName: "Shrestha",
  email: "anya@example.com",
  memberSince: "2024-03-14",
  interests: ["tea", "ceramic", "wellness"],
};

export const orders: Order[] = [
  {
    id: "ord_1042",
    displayId: "#IT-1042",
    date: "2026-08-02",
    status: "shipped",
    total: { amount: 6800, currency: "usd" },
    items: [
      { title: "Ilam First Flush Black Tea", quantity: 2, image: images.tea },
      { title: "Terra Stoneware Cup & Saucer", quantity: 1, image: images.ceramic },
    ],
  },
  {
    id: "ord_1017",
    displayId: "#IT-1017",
    date: "2026-06-21",
    status: "delivered",
    total: { amount: 18500, currency: "usd" },
    items: [{ title: "Ridge Cashmere Shawl", quantity: 1, image: images.pashmina }],
  },
  {
    id: "ord_0988",
    displayId: "#IT-0988",
    date: "2026-05-09",
    status: "delivered",
    total: { amount: 5000, currency: "usd" },
    items: [{ title: "Wild Cliff Honey", quantity: 1, image: images.honey }],
  },
];
