/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as NepalOriginRouteImport } from './routes/nepal-origin'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategoryHandleRouteImport } from './routes/category.$handle'
import { Route as CollectionHandleRouteImport } from './routes/collection.$handle'
import { Route as OrderConfirmedRouteImport } from './routes/order.confirmed'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as VendorHandleRouteImport } from './routes/vendor.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const NepalOriginRoute = NepalOriginRouteImport.update({
  id: '/nepal-origin',
  path: '/nepal-origin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryHandleRoute = CategoryHandleRouteImport.update({
  id: '/category/$handle',
  path: '/category/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionHandleRoute = CollectionHandleRouteImport.update({
  id: '/collection/$handle',
  path: '/collection/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order/confirmed',
  path: '/order/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorHandleRoute = VendorHandleRouteImport.update({
  id: '/vendor/$handle',
  path: '/vendor/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/nepal-origin': typeof NepalOriginRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$handle': typeof CategoryHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/order/confirmed': typeof OrderConfirmedRoute
  '/product/$handle': typeof ProductHandleRoute
  '/vendor/$handle': typeof VendorHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/nepal-origin': typeof NepalOriginRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$handle': typeof CategoryHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/order/confirmed': typeof OrderConfirmedRoute
  '/product/$handle': typeof ProductHandleRoute
  '/vendor/$handle': typeof VendorHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/nepal-origin': typeof NepalOriginRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$handle': typeof CategoryHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/order/confirmed': typeof OrderConfirmedRoute
  '/product/$handle': typeof ProductHandleRoute
  '/vendor/$handle': typeof VendorHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/nepal-origin'
    | '/shop'
    | '/vendors'
    | '/wishlist'
    | '/category/$handle'
    | '/collection/$handle'
    | '/order/confirmed'
    | '/product/$handle'
    | '/vendor/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/nepal-origin'
    | '/shop'
    | '/vendors'
    | '/wishlist'
    | '/category/$handle'
    | '/collection/$handle'
    | '/order/confirmed'
    | '/product/$handle'
    | '/vendor/$handle'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/nepal-origin'
    | '/shop'
    | '/vendors'
    | '/wishlist'
    | '/category/$handle'
    | '/collection/$handle'
    | '/order/confirmed'
    | '/product/$handle'
    | '/vendor/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  NepalOriginRoute: typeof NepalOriginRoute
  ShopRoute: typeof ShopRoute
  VendorsRoute: typeof VendorsRoute
  WishlistRoute: typeof WishlistRoute
  CategoryHandleRoute: typeof CategoryHandleRoute
  CollectionHandleRoute: typeof CollectionHandleRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  ProductHandleRoute: typeof ProductHandleRoute
  VendorHandleRoute: typeof VendorHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nepal-origin': {
      id: '/nepal-origin'
      path: '/nepal-origin'
      fullPath: '/nepal-origin'
      preLoaderRoute: typeof NepalOriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$handle': {
      id: '/category/$handle'
      path: '/category/$handle'
      fullPath: '/category/$handle'
      preLoaderRoute: typeof CategoryHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$handle': {
      id: '/collection/$handle'
      path: '/collection/$handle'
      fullPath: '/collection/$handle'
      preLoaderRoute: typeof CollectionHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/confirmed': {
      id: '/order/confirmed'
      path: '/order/confirmed'
      fullPath: '/order/confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$handle': {
      id: '/vendor/$handle'
      path: '/vendor/$handle'
      fullPath: '/vendor/$handle'
      preLoaderRoute: typeof VendorHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  NepalOriginRoute: NepalOriginRoute,
  ShopRoute: ShopRoute,
  VendorsRoute: VendorsRoute,
  WishlistRoute: WishlistRoute,
  CategoryHandleRoute: CategoryHandleRoute,
  CollectionHandleRoute: CollectionHandleRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  ProductHandleRoute: ProductHandleRoute,
  VendorHandleRoute: VendorHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
